"""Tune nominal LC/RB gains against the real VGC simulation loop.

Examples:
    python run/optimize_gains.py --coriolis lc --write
    python run/optimize_gains.py --coriolis all --duration 10 --maxiter 20
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

import numpy as np
from scipy.optimize import differential_evolution

ROOT = Path(__file__).resolve().parent.parent
sys.path[:0] = [str(ROOT), str(ROOT / "src")]

from vgc.config.manual_gains import manual_gains
from vgc.config.optimized_gains import optimized_gains
from vgc.io.persistence import atomic_write_json
from vgc.sim.default_scenario import default_scenario
from vgc.sim.metrics import compute_metrics
from vgc.sim.run_scenario import run_scenario


GAIN_KEYS = ("KRdiag", "Kxidiag", "LambdaDiag", "kd", "ks", "alpha")
BOUNDS = ((1e-3, 100.0),) * 3 + ((1e-3, 100.0),) * 3 + ((1e-3, 100.0),) * 6 + ((1e-3, 100.0),) * 2 + ((0.1, 0.99),)


def gain_vector(gains: dict) -> np.ndarray:
    """Flatten the nominal gain dictionary into the optimizer's 15-vector."""
    return np.concatenate([
        np.asarray(gains["KRdiag"], dtype=float).ravel(),
        np.asarray(gains["Kxidiag"], dtype=float).ravel(),
        np.asarray(gains["LambdaDiag"], dtype=float).ravel(),
        [float(gains["kd"]), float(gains["ks"]), float(gains["alpha"])],
    ])


def gains_from_vector(vector: np.ndarray) -> dict:
    """Convert a 15-vector back to the controller gain dictionary."""
    values = np.asarray(vector, dtype=float).ravel()
    if values.shape != (15,):
        raise ValueError(f"Expected 15 gain values, got {values.shape}.")
    return {
        "KRdiag": values[0:3].copy(),
        "Kxidiag": values[3:6].copy(),
        "LambdaDiag": values[6:12].copy(),
        "kd": float(values[12]),
        "ks": float(values[13]),
        "alpha": float(values[14]),
    }


def tracking_cost(metrics: dict) -> float:
    """Score tracking quality in physical units; failed runs are infeasible."""
    return float(
        metrics["positionRMSE"]
        + 0.25 * metrics["attitudeRMSE"]
        + 0.05 * metrics["linearVelocityRMSE"]
        + 0.05 * metrics["angularVelocityRMSE"]
        + 0.001 * metrics["forceRMS"]
        + 0.001 * metrics["torqueRMS"]
    )


def evaluate_candidate(vector: np.ndarray, *, coriolis: str, replay_id: str, duration: float) -> float:
    gains = gains_from_vector(vector)
    scenario = default_scenario(
        replay_id=replay_id,
        coriolis=coriolis,
        duration=duration,
        gain_override=gains,
        enable_pacing=False,
    )
    run, failure = run_scenario(scenario)
    if failure is not None or len(run["t"]) < 2:
        return 1.0e9
    return tracking_cost(compute_metrics(run))


def optimize_variant(coriolis: str, *, replay_id: str, duration: float, seed: int,
                     maxiter: int, popsize: int) -> tuple[dict, float]:
    baseline = optimized_gains("nominal", coriolis)
    baseline_vector = gain_vector(baseline)
    baseline_cost = evaluate_candidate(baseline_vector, coriolis=coriolis, replay_id=replay_id, duration=duration)
    if coriolis == "rb":
        # The predecessor RB seed is not a stable starting point for this
        # nominal trajectory. Keep the measured LC seed as a safe fallback.
        stable_seed = manual_gains("nominal", "lc")
        stable_vector = gain_vector(stable_seed)
        stable_cost = evaluate_candidate(stable_vector, coriolis=coriolis, replay_id=replay_id, duration=duration)
        if stable_cost < baseline_cost:
            baseline, baseline_vector, baseline_cost = stable_seed, stable_vector, stable_cost
    result = differential_evolution(
        lambda candidate: evaluate_candidate(candidate, coriolis=coriolis, replay_id=replay_id, duration=duration),
        bounds=BOUNDS,
        x0=baseline_vector,
        seed=seed,
        maxiter=maxiter,
        popsize=popsize,
        polish=True,
        updating="immediate",
        workers=1,
    )
    if result.fun > baseline_cost:
        return baseline, baseline_cost
    return gains_from_vector(result.x), float(result.fun)


def write_registry(results: dict, path: Path) -> None:
    lines = ["\"\"\"Optimized nominal gain registry generated by run/optimize_gains.py.\"\"\"", "", "import numpy as np", "", "", "def optimized_gains(mode: str, coriolis: str) -> dict:", "    if str(mode).lower() != 'nominal':", "        raise ValueError(f'Only nominal gains are available, got {mode!r}')", "    key = str(coriolis).lower()", "    registry = {"]
    for key, gains in results.items():
        lines.append(f"        {key!r}: {{")
        for name in ("KRdiag", "Kxidiag", "LambdaDiag"):
            lines.append(f"            {name!r}: np.array({np.asarray(gains[name]).tolist()!r}, dtype=float),")
        for name in ("kd", "ks", "alpha"):
            lines.append(f"            {name!r}: {float(gains[name])!r},")
        lines.append("        },")
    lines += ["    }", "    if key not in registry:", "        raise ValueError(f'Unknown Coriolis form: {coriolis!r}')", "    return {k: (v.copy() if isinstance(v, np.ndarray) else v) for k, v in registry[key].items()}", ""]
    path.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser(description="Optimize nominal VGC tracking gains.")
    parser.add_argument("--coriolis", choices=("lc", "rb", "all"), default="all")
    parser.add_argument("--replay-id", default="lemniscate_01_auto")
    parser.add_argument("--duration", type=float, default=10.0)
    parser.add_argument("--seed", type=int, default=20261004)
    parser.add_argument("--maxiter", type=int, default=20)
    parser.add_argument("--popsize", type=int, default=8)
    parser.add_argument("--output", type=Path, default=ROOT / "results" / "optimization" / "nominal_gains.json")
    parser.add_argument("--write", action="store_true", help="Write src/vgc/config/optimized_gains.py after tuning")
    args = parser.parse_args()
    forms = ("lc", "rb") if args.coriolis == "all" else (args.coriolis,)
    results = {}
    report = {}
    for index, form in enumerate(forms):
        gains, cost = optimize_variant(form, replay_id=args.replay_id, duration=args.duration,
                                       seed=args.seed + index, maxiter=args.maxiter, popsize=args.popsize)
        results[form] = gains
        report[form] = {"cost": cost, "gains": gains}
        print(f"{form.upper()}: cost={cost:.8g}")
    atomic_write_json(args.output, report)
    if args.write:
        write_registry(results, ROOT / "src" / "vgc" / "config" / "optimized_gains.py")


if __name__ == "__main__":
    main()
