"""Optimized nominal gain registry generated by run/optimize_gains.py."""

import numpy as np


def optimized_gains(mode: str, coriolis: str) -> dict:
    if str(mode).lower() != 'nominal':
        raise ValueError(f'Only nominal gains are available, got {mode!r}')
    key = str(coriolis).lower()
    registry = {
        'lc': {
            'KRdiag': np.array([0.10533378554572626, 0.11038644612727647, 0.06751355095472227], dtype=float),
            'Kxidiag': np.array([31.95969930561908, 25.523495705283572, 8.666304395220438], dtype=float),
            'LambdaDiag': np.array([46.79063913592169, 29.14884795370729, 21.131151474955242, 0.4501915634612157, 0.3398188899295195, 2.0896863700504213], dtype=float),
            'kd': 14.137666754475394,
            'ks': 10.310140555669898,
            'alpha': 0.6579275252160727,
        },
        'rb': {
            'KRdiag': np.array([0.03598136926734239, 0.8489613043595274, 0.36734864373128145], dtype=float),
            'Kxidiag': np.array([31.94153240810013, 25.52845754929727, 8.804737905839678], dtype=float),
            'LambdaDiag': np.array([46.69823847204407, 29.221296992140633, 21.126180439267433, 0.712851989457644, 0.3177105124283059, 0.49022720094727723], dtype=float),
            'kd': 14.14977809920105,
            'ks': 10.27532246206712,
            'alpha': 0.6723393378873974,
        },
    }
    if key not in registry:
        raise ValueError(f'Unknown Coriolis form: {coriolis!r}')
    return {k: (v.copy() if isinstance(v, np.ndarray) else v) for k, v in registry[key].items()}
